<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Composer Routes
|--------------------------------------------------------------------------
|
| These routes are for Composer to access the repository.
| They act as a proxy for the files generated by Satis and its wrappers.
| All calls to these routes are gated by HTTP Basic Authentication for
| user "token" and a GitHub access token with access to the organization's
| private repositories
|
*/

Route::get('search/{query}', 'RepositoryController@search')
    ->name('search')
    ->where('query', '.*');
Route::get('packages.json', 'RepositoryController@serve');
Route::get('p/{query}', 'RepositoryController@serve')->where('query', '.*');
